version: '3'

services:
  keycloak:
    container_name: keycloak
    depends_on: 
      - "postgresqldb"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresqldb
      DB_DATABASE: kaliber_keycloak_db
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JDBC_PARAMS: "useSSL=false"
    image: jboss/keycloak:12.0.0
    volumes: 
      - ./Keycloak_conf/:/opt/jboss/keycloak/imports
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    ports:
      - '8100:8080'
      - '8443:8443'
    networks: 
      - internal

  backend:
    container_name: backend
    build:
      context: "./"
    depends_on: 
      - "keycloak"
      - "postgresqldb"
    environment: 
      SERVER_IP: 130.61.186.61
      SERVICE_KEYCLOAK_REALM: OrngAuth
      SERVICE_KEYCLOAK_BACKEND_CLIENT: admin-backend
      SERVICE_KEYCLOAK_BACKEND_CLIENT_SECRET: d063d8ac-d63b-4ea2-88e9-cb794a062d8a
      POSTGRES_DB_URL: jdbc:postgresql://postgresqldb:5432/kaliber_db
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      #email
      MAIL_SERVICE_HOST: smtp.gmail.com
      MAIL_SERVICE_PORT: 587
      MAIL_SERVICE_USERNAME: bp.qneds.test@gmail.com
      MAIL_SERVICE_HOST_PASSWORD: ""

      SERVICE_KEYCLOAK_SWAGGER_CLIENT: orange-backend
      SERVICE_KEYCLOAK_SWAGGER_CLIENT_SECRET: 86d2938e-2474-4f2f-b936-cae6c875fad1
      SERVICE_KEYCLOAK_FRONT_CLIENT: orange-app
      SERVICE_KEYCLOAK_FRONT_CLIENT_SWAGGER: a6c73d18-cdfa-49e3-bfb9-9d4f2640c1cf
      DB_ON_LAUNCH_MODE: update
      #DB_ON_LAUNCH_MODE: create-drop

    ports:
      - "9000:9000"
    links: 
      - "keycloak:keycloak"
    networks: 
      - internal
  

  postgresqldb:
    container_name: postgresqldb
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Kaliber
    #links:
      #- "postgresqldb:postgresqldb"
    volumes: 
      - ./sql/init_keycloak_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - internal

  backend:
    container_name: backend
    build:
      context: "./"
    depends_on: 
      - "keycloak"
      - "postgresqldb"
    environment: 
      SERVER_IP: 130.61.186.61
      SERVICE_KEYCLOAK_REALM: OrngAuth
      SERVICE_KEYCLOAK_BACKEND_CLIENT: admin-backend
      SERVICE_KEYCLOAK_BACKEND_CLIENT_SECRET: d063d8ac-d63b-4ea2-88e9-cb794a062d8a
      POSTGRES_DB_URL: jdbc:postgresql://postgresqldb:5432/kaliber_db
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      #email
      MAIL_SERVICE_HOST: smtp.gmail.com
      MAIL_SERVICE_PORT: 587
      MAIL_SERVICE_USERNAME: bp.qneds.test@gmail.com
      MAIL_SERVICE_HOST_PASSWORD: ""

      SERVICE_KEYCLOAK_SWAGGER_CLIENT: orange-backend
      SERVICE_KEYCLOAK_SWAGGER_CLIENT_SECRET: 86d2938e-2474-4f2f-b936-cae6c875fad1
      SERVICE_KEYCLOAK_FRONT_CLIENT: orange-app
      SERVICE_KEYCLOAK_FRONT_CLIENT_SWAGGER: a6c73d18-cdfa-49e3-bfb9-9d4f2640c1cf
      DB_ON_LAUNCH_MODE: update
      #DB_ON_LAUNCH_MODE: create-drop

    ports:
      - "9000:9000"
    links: 
      - "keycloak:keycloak"
    networks: 
      - internal

  frontend:
    container_name: frontend
    build:
      context: "./orange-meet/"
    depends_on: 
      - "keycloak"
      - "postgresqldb"
      - "backend"
    links: 
      - "backend:backend"
    ports:
      - "8080:80"
    networks: 
      - internal

networks: 
  internal: 
    driver: bridge


