# application configuration
server:
  port: 9000
  http: http://
  https: https://
  #ip: 130.61.186.61
  ip: ${SERVER_IP}
  url: ${server.http}${server.ip}
  #url: http://130.61.186.61
  #url: http://localhost

# keycloak configuration
keycloak:
  # name of the created realm
  #enabled: false
  #realm: OrngAuth
  realm: ${SERVICE_KEYCLOAK_REALM}
  # name of the created client
  #resource: admin-backend
  resource: ${SERVICE_KEYCLOAK_BACKEND_CLIENT}
  #resource: orange-backend
  # indicates that our service has been created as a bearer-only (by default it is false)
  bearer-only: true
  # url of our Keycloak server
  #auth-server-url: http://130.61.186.61:8100/auth
  auth-server-url: ${server.url}:8100/auth
  ssl-required: none
  #public-client: false
  credentials:
    secret: ${SERVICE_KEYCLOAK_BACKEND_CLIENT_SECRET}
    #secret: ba0a99ad-340f-48f4-9538-89db097a9546 #server
    #secret: 7cf7873c-298d-4bdd-976e-59258a52507e #localhost

spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    #url: jdbc:postgresql://postgresqldb:5432/Omeet #server
    #url: jdbc:postgresql://localhost:5432/Omeet #localhost
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    #username: postgres
    #password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      #ddl-auto: update
      ddl-auto: ${DB_ON_LAUNCH_MODE}
      #ddl-auto: create-drop
  #autoconfigure:
    #exclude:
      #- org.keycloak.adapters.springboot.KeycloakSpringBootConfiguration
  mail:
    host: ${MAIL_SERVICE_HOST}
    port: ${MAIL_SERVICE_PORT}
    username: ${MAIL_SERVICE_USERNAME}
    password: ${MAIL_SERVICE_HOST_PASSWORD}
    #host: smtp.gmail.com
    #port: 587
    #username: bp.qneds.test@gmail.com
    #password: "mango swiersz sztorm"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

swagger:
  auth:
    token-url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token/
    auth-url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth/
    client-id: ${SERVICE_KEYCLOAK_SWAGGER_CLIENT}
    secret: ${SERVICE_KEYCLOAK_SWAGGER_CLIENT_SECRET}
    #client-id: orange-backend
    #secret: 8377ed9c-abf2-43f8-a712-4c8a93a1b784 #server
    #secret: 9a612258-970b-4896-b368-58865914fefe #localhost

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

auth:
  client: ${SERVICE_KEYCLOAK_FRONT_CLIENT}
  secret: ${SERVICE_KEYCLOAK_FRONT_CLIENT_SWAGGER}
  #client: orange-app
  #secret: 881f08d9-7da9-4654-a3b2-8987b7a17506 #server
  #secret: 3a9266bb-4ca5-4615-9f6d-934bd2a3afad #localhost


