# application configuration
server:
  port: 9000
  url: http://130.61.186.61
  #url: http://localhost

# keycloak configuration
keycloak:
  # name of the created realm
  #enabled: false
  realm: OrngAuth
  # name of the created client
  resource: admin-backend
  #resource: orange-backend
  # indicates that our service has been created as a bearer-only (by default it is false)
  bearer-only: true
  # url of our Keycloak server
  #auth-server-url: http://130.61.186.61:8100/auth
  auth-server-url: ${server.url}:8100/auth
  ssl-required: none
  #public-client: false
  credentials:
    #secret: 7cf7873c-298d-4bdd-976e-59258a52507e #localhost
    secret: ba0a99ad-340f-48f4-9538-89db097a9546 #server

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/Omeet
    url: jdbc:postgresql://postgresqldb:5432/Omeet
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
  #autoconfigure:
    #exclude:
      #- org.keycloak.adapters.springboot.KeycloakSpringBootConfiguration
  mail:
    host: smtp.gmail.com
    port: 587
    username: bp.qneds.test@gmail.com
    password: "mango swiersz sztorm"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

swagger:
  auth:
    token-url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token/
    auth-url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth/
    client-id: orange-backend
    secret: 8377ed9c-abf2-43f8-a712-4c8a93a1b784 #server
    #secret: 9a612258-970b-4896-b368-58865914fefe #localhost

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

#orange-app secret: f0a42c65-a82a-431c-b4e6-36985039a434

